#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php'; 

// import the Symfony Console Application 
use Symfony\Component\Console\Application; 
use Algenza\Json\Mocker\Cli\GenerateDataCommand;

$app = new Application('Fake Json Generator','0.1.0');

$app->add(new GenerateDataCommand());

$app->run();
?>